version: '3.8'

services:
  blockchain-node:
    image: ethereum/client-go:latest
    container_name: akoya-moon-node
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ./blockchain/data:/root/.ethereum
      - ./blockchain/genesis.json:/genesis.json
      - ./blockchain/password.txt:/password.txt
    command: >
      --datadir /root/.ethereum
      init /genesis.json;
      geth --datadir /root/.ethereum
           --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "admin,debug,web3,eth,txpool,personal,clique,miner,net"
           --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api "admin,debug,web3,eth,txpool,personal,clique,miner,net"
           --allow-insecure-unlock
           --unlock 0xa1b2c3d4e5f67890123456789012345678901234
           --password /password.txt
           --mine
           --miner.etherbase 0xa1b2c3d4e5f67890123456789012345678901234
           --networkid 17771
           --identity "AkoyaMoonTestnet"
    restart: unless-stopped

  faucet-api:
    image: node:18
    container_name: akoya-moon-faucet
    ports:
      - "3000:3000"
    volumes:
      - ./faucet:/app
      - ./faucet/storage:/app/storage
    working_dir: /app
    environment:
      - NODE_ENV=production
      - RPC_URL=http://blockchain-node:8545
      - FAUCET_PRIVATE_KEY=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - blockchain-node
    restart: unless-stopped